In [2]:

import numpy as np
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)


[0 1 2 3 4 5 6 7 8 9]


In [3]:
my_list = [3.14, 2.17, 0, 1, 2]
p = np.array(my_list, dtype=int)
p


array([3, 2, 0, 1, 2])

In [4]:
my_array = np.arange(1, 10).reshape(3, 3)
my_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
random_array = np.random.rand(4, 5)
random_array = np.round(random_array, 2)
random_array


array([[0.23, 0.8 , 0.13, 0.85, 0.59],
       [0.4 , 0.5 , 0.1 , 0.38, 0.05],
       [0.16, 0.67, 0.92, 0.88, 0.91],
       [0.21, 0.17, 0.06, 0.08, 0.13]])

In [9]:
my_array = np.arange(1, 10).reshape(3, 3)
print(my_array)
second_row = my_array[1, :]
second_row


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 5, 6])

In [10]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reversed_array = np.flip(array)
reversed_array


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
import numpy as np

identity_matrix = np.eye(4)
identity_matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sum_of_elements = np.sum(array)
print("Sum:", sum_of_elements)

average_of_elements = np.mean(array)
print("Average:", average_of_elements)


Sum: 45
Average: 4.5


In [13]:
my_array = np.arange(1, 21)

reshaped_array = my_array.reshape(4, 5)

reshaped_array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
odd_numbers = array[array % 2 != 0]
odd_numbers


array([1, 3, 5, 7, 9])